# Agent 应用配置文件

# Redis 配置
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  protocol: 2
  unstable_resp3: true

# 大语言模型配置
llm:
  base_url: "http://192.168.124.1:11434"
  model: "qwen3:4b"
  timeout: 60s

# RAG 配置
rag:
  index_name: "rag_index"
  prefix: "rag_prefix:"
  dimension: 2560
  vector_field: "vector_content"
  top_k: 3
  dialect: 2
  return_fields:
    - "vector_content"
    - "content"

embedding:
  model: "doubao-embedding-text-240715"
  api_key: "api-key"